### ISSUE TITLE
[Feature Request] 請問有無考慮加上別名和通配符？

### ISSUE THREAD

**Issue by dqwyy** [rime/rime-stroke#2]
n（捺）又名d（點）
h（橫）又名t（提）
統配符即萬用鍵，像之前的按鍵機上面有的那個鍵一樣。

如果我要實現上述別名，請問該如何操作呢？
我嘗試打了下面的補丁

```yaml
patch:
  speller/algebra:
    - derive/n/d/
    - derive/h/t/
```

結果在打字的時候，一個字中單用h可以打，單用t也可以打，但是兩者混用就不可以打了，例如說要打「三」，如果打`hhh`可以打，打`ttt`也可，但是打`hht`就打不出來。請問如何解決？
